name: "Csscading Auto-Merge Action"
description: "GitHub action to automatically merge downstream branches based on semantic versioning"

inputs:
  prefixes:
    description: 'prefixes'
    required: true
  refBranch:
    description: 'refBranch'
    required: true
  pullNumber:
    description: 'pullNumber'
    required: true  
    
runs:
  using: node12
  main: src/index.js

branding:
  icon: 'check-square'  
  color: 'green'
