---
name: GitHub Actions Demo

on: workflow_dispatch
    inputs:
      template:
        type: string
        description: template (.github/PROJECT_TEMPLATES/)
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization
        
      - run: npm install @octokit/action
      - run: npm install @actions/github
      - run: npm install @actions/core  
      # Run the local action code
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
